### ISSUE TITLE
[Alexandria Labs] <Unable to delegate access to capacity credit>

### ISSUE THREAD

**Issue by robyn3choi** [LIT-Protocol/Issues-and-Reports#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

4.2.0

### Lit Network

habanero

### Description of the bug/issue

We are unable to successfully run [the example in the docs for delegating access to a capacity credit NFT](https://developer.litprotocol.com/v3/sdk/capacity-credits#delegating-access-to-your-capacity-credits-nft). I created [this demo repo](https://github.com/robyn3choi/lit-issue) that reproduces the error. 

When you run that repo's `main` branch and try to delegate access, an error is thrown with the message: `TypeError: invalid BytesLike value`. Here's a screenshot of the error in the browser console:

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/9066587/5ee47b20-e649-4fbc-89d3-c021a93a678a)

In the repo's `downgraded-packages` branch, I downgraded the repo's `ethers` and `siwe` packages to the same versions used in Lit's packages, and we get an error with the message `signature missing v and recoveryParam` instead. 

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/9066587/b0efdfb6-fead-4fae-8277-b05b270b38f3)

### Severity of the bug

High severity - it's blocking us from using the latest Lit SDK, so we're still using the v2 SDK.

### Steps To Reproduce

1. Clone the repo at https://github.com/robyn3choi/lit-issue
2. In src/lit.ts, replace `capacityTokenId` on line 42 with your capacity token's ID.
3. Run `yarn` to install packages
4. Run `yarn dev` to run the app locally
5. Click the "Delegate capacity" button

### Link to code

https://github.com/robyn3choi/lit-issue

**Comment by Aaryan-R-S** [comment]
The old auth sig which is stored in browser's local storage is presented to Lit nodes on recompilation and hence, throw this error (it's not valid anymore).

To avoid this error message, just clear the local storage and everything will work fine: [https://developer.litprotocol.com/v3/sdk/authentication/auth-sig#clearing-local-storage](https://developer.litprotocol.com/v3/sdk/authentication/auth-sig#clearing-local-storage) 

```javascript
itJsSdk.disconnectWeb3();
```

**Comment by robyn3choi** [comment]
I tried clearing my browser's local storage in the dev tools as well as calling `LitJsSdk.disconnectWeb3()` right before calling `await client.connect()` and I still get the same errors. There is this new message in the browser console now though: 
![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/9066587/ad1814a9-214a-49e4-bedc-abecfe67eeb9)

**Comment by robyn3choi** [comment]
I just made a couple updates to the `main` branch and pushed
- installed `@lit-protocol/lit-node-client` 5.0.0
- call `LitJsSdk.disconnectWeb3()`

I get these new browser console messages after these changes:

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/9066587/fa816b9a-cdc6-4d2d-a5fd-441f2debf8f4)

**Comment by Aaryan-R-S** [comment]
Hey @robyn3choi!

You're right. These warnings are there. I'm not sure about these. I've fwd this to our SDK team.

Are there any "errors" that you are seeing on console?

**Comment by robyn3choi** [comment]
Just the errors I've described in the description in the original post above

**Comment by robyn3choi** [comment]
Has the team been able to run the https://github.com/robyn3choi/lit-issue repo without those errors?

**Comment by Aaryan-R-S** [comment]
Yup! I'm not getting any error. 
I've modified lit.ts little bit. Here is the complete code:
```js
import { SiweMessage } from "siwe";
import { ethers } from "ethers";
import * as LitJsSdk from "@lit-protocol/lit-node-client";
import { LitAbility, LitActionResource } from "@lit-protocol/auth-helpers";

const client = new LitJsSdk.LitNodeClient({
  litNetwork: "habanero",
  alertWhenUnauthorized: false,
  checkNodeAttestation: true,
  debug:true
});

class Lit {
  private litNodeClient;

  async connect() {
    await client.connect();
    this.litNodeClient = client;
  }

  async delegateCapacity() {
    try {
      if (!this.litNodeClient) {
        LitJsSdk.disconnectWeb3();
        await this.connect();
      }
      // @ts-ignore
      const provider = new ethers.BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();

      const { capacityDelegationAuthSig } =
        await this.litNodeClient!.createCapacityDelegationAuthSig({
          uses: "1",
          dAppOwnerWallet: signer,
          capacityTokenId: "959", // replace with your token id
          domain: window.location.host,
        });

      console.log("capacityDelegationAuthSig", capacityDelegationAuthSig);

      const authNeededCallback = async ({ resources, expiration, uri }) => {
        console.log("authneededcallback");

        const litResource = new LitActionResource("*");

        const recapObject =
          await this.litNodeClient!.generateSessionCapabilityObjectWithWildcards(
            [litResource]
          );

        recapObject.addCapabilityForResource(
          litResource,
          LitAbility.LitActionExecution
        );

        const verified = recapObject.verifyCapabilitiesForResource(
          litResource,
          LitAbility.LitActionExecution
        );

        if (!verified) {
          throw new Error("Failed to verify capabilities for resource");
        }

        const nonce = await this.litNodeClient!.getLatestBlockhash();
        console.log("nonce: ", nonce);

        let siweMessage = new SiweMessage({
          domain: window.location.host,
          address: signer.address,
          statement: "Some custom statement.",
          uri,
          version: "1",
          chainId: 1,
          expirationTime: expiration,
          resources,
          nonce,
        });

        siweMessage = recapObject.addToSiweMessage(siweMessage);

        const messageToSign = siweMessage.prepareMessage();
        const signature = await signer.signMessage(messageToSign);

        const authSig = {
          sig: signature,
          derivedVia: "web3.eth.personal.sign",
          signedMessage: messageToSign,
          address: signer.address,
        };
        console.log("authSig: ", authSig);
        return authSig;
      };
      const sessionSigs = await this.litNodeClient.getSessionSigs({
        expiration: new Date(Date.now() + 1000 * 60 * 60).toISOString(), // 1 hr
        chain: "ethereum",
        resourceAbilityRequests: [
          {
            resource: new LitActionResource("*"),
            ability: LitAbility.LitActionExecution,
          },
        ],
        authNeededCallback,
        capacityDelegationAuthSig,
      });
      console.log("sessionSigs: ", sessionSigs);
      return sessionSigs;
    } catch (err: any) {
      console.error(err);
    }
  }
}

export default new Lit();
```

Rest is unchanged!

**Comment by Aaryan-R-S** [comment]
I'm only getting warning as mentioned by you (will revert on those).
I'm not getting any error. Try out the above code please.

**Comment by robyn3choi** [comment]
Your code works without errors, thanks!

**Comment by Aaryan-R-S** [comment]
Hey @robyn3choi! You can safely ignore these warnings. 

The first warning means you don't have a signature already in local storage to use as the inner auth sig when attempting to generate a session signature.

The other warning is about the siwe library validate method being deprecated for the verify implementation within that package.
