### ISSUE TITLE
Aarc contractCall from within the lit action is not working.

### ISSUE THREAD

**Issue by anshulforyou** [LIT-Protocol/Issues-and-Reports#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

LitNodeClient, v4.2.0

### Lit Network

habanero

### Description of the bug/issue

The callContract function of lit action is giving an error. 

logs: 'Contract address - 0x11329FBbD06313265083596f04CAB23368A10439, provider-index 1\n' +
    'rawTran  {\n' +
    '  data: "0x913a2ffe0000000000000000000000000000000000000000000000000000000000000001",\n' +
    '  to: "0x11329FBbD06313265083596f04CAB23368A10439"\n' +
    '}\n' +
    'txn  0xf83e8080809411329fbbd06313265083596f04cab23368a1043980a4913a2ffe0000000000000000000000000000000000000000000000000000000000000001\n' +
    'Smart Contract Error: failed to fetch secondary Lit action cid:  Error: Deserialization Error: expected value at line 1 column 1. Response: error code: 1015\n' +

### Severity of the bug

High

### Steps To Reproduce

Just try to call a contract from inside a lit action. I have added the logs above. U can use the same contract as well. It is deployed on eth sepolia.

### Link to code

IPFS CID of the lit action from which we are making the contract call QmeaTg8wLzW1Ltb2qBG7NCwS4TnizmrGRWrZxebdNE74S3

**Comment by glitch003** [comment]
@anshulforyou can you provide the code you're using to create the serialized contract call?

**Comment by anshulforyou** [comment]
I have mentioned the ipfs cid. It contains the lit action code.

**Comment by glitch003** [comment]
it appears that sepolia is not working on Habanero.  I was able to redeploy our test contract to "optimism" and it seems to work there.  Here's my example lit action code which is working on optimism:

```
const go = async () => {
    // https://sepolia.etherscan.io/address/0xD2f13AeACd77bB8D0aD79c6dB5F081e358b481C2#code
    // on optimism (for testing there) https://optimistic.etherscan.io/address/0x4ddd5Bd269dad12b6a381a22dd663dF811031a61#code
    const toContract = "0x4ddd5Bd269dad12b6a381a22dd663dF811031a61";

    const abi = [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[{"internalType":"uint256","name":"a","type":"uint256"},{"internalType":"uint256","name":"b","type":"uint256"}],"name":"add","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];

    const contract = new ethers.Contract(toContract, abi);
    const rawTxn = await contract.populateTransaction.add(1,2);
    const txn = ethers.utils.serializeTransaction(rawTxn);
    
    const chain = "optimism";

    const res = await Lit.Actions.callContract({
        chain,
        txn
    });

    // decode response
    const decodedResult = contract.interface.decodeFunctionResult("add", res)[0].toString();

    Lit.Actions.setResponse({response: decodedResult});
};
go();
```

In the meantime, I will investigate why Sepolia is down on habanero and fix it.
