### ISSUE TITLE
Documentation for running a local Lit Network

### ISSUE THREAD

**Issue by trmrtn** [LIT-Protocol/Issues-and-Reports#12]
### Description of the issue

I am playing around with Lit Protocol and wanted to run my own local private network.
I found these instructions, and would like to know if they are the best to follow currently:
https://github.com/LIT-Protocol/Node/blob/main/rust/lit-node/README.md#setting-up-local-network

In the above instructions, the link in Step 1 (deploy & configure Lit smart contracts) is broken. So for Step 1, should I instead follow the instructions here: https://github.com/LIT-Protocol/Node/tree/main/blockchain/contracts#local-deployment

**Comment by humblemodulo** [comment]
Hrm, giving this a go on M1 Max (each from their appropriate directories):

- `npx hardhat node` (successfully start up local evm)
- `npm run deploy -- --deploy-config deploy.config.json` (successfully deploy lit contracts)
- `make setup-local-files` (put config items in place for starting lit node)
-  `./scripts/start_dev.sh 3` (attempt to actually deploy the previously stipulated number of nodes)

The deployment attempt of `start_dev.sh` fails with:  

```
[0] info: latest update on 2023-09-11, rust version 1.74.0-nightly (030e4d382 2023-09-10)
[0] info: downloading component 'cargo'
[0] info: downloading component 'clippy'
[0] info: downloading component 'rust-docs'
[0] info: downloading component 'rust-src'
[0] RUST_LOG=warn,lit_node=trace LIT_CONFIG_FILE=./config/lit_config0.toml cargo run --features lit-actions exited with code SIGTERM
```

Is there some completely obvious item I'm missing?
