### ISSUE TITLE
Access Control Condition Required for Encryption/Decryption?

### ISSUE THREAD

**Issue by spacesailor24** [LIT-Protocol/Issues-and-Reports#15]
### Description of the issue

[From Discord](https://discord.com/channels/896185694857343026/1230196290701230141/1230196290701230141):

> Is an Access Control Condition that checks state on a blockchain required when calling the encryptString/encryptFile/etc methods? Can it be empty and have encryption/decryption only require the authSig?

**Comment by spacesailor24** [comment]
A control condition seems to be required. A simple, always true, condition such as:

```
const accessControlConditions = [
    {
      contractAddress: "",
      standardContractType: "timestamp",
      chain: "ethereum",
      method: "",
      parameters: [],
      returnValueTest: {
        comparator: ">=",
        value: "0",
      },
    },
  ];
```

can be used as a workaround. I will follow up if there's a better solution proposed by one of our devs. In the meantime, please let me know if you have any other questions!

**Comment by spacesailor24** [comment]
@trmrtn No problem!

From my testing (and [this constant](https://github.com/LIT-Protocol/js-sdk/blob/83a070bd2820e3534654313ea9f6688e7add897f/packages/constants/src/lib/constants/constants.ts#L35)), it looks like `chain` has to be one of the supported EVM chains, else an error is thrown. I will double check with the devs though

**Comment by trmrtn** [comment]
This might be an interesting workaround regarding ACC on non-supported chains, though haven't tried it out myself yet...
If I wanted to check state on a non-supported chain as an ACC, then I can try setting the ACC's `contractAddress` as a LitAction that makes a call to a node provider for an unsupported chain to pull whatever state I'm interested in.

**Comment by spacesailor24** [comment]
@trmrtn Just confirmed that `chain` does need to be apart of the supported list

Your workaround seems sound!

**Comment by spacesailor24** [comment]
Going to close this issue as completed, but feel free to add to it, or message me on Discord if you have any follow ups!

**Comment by spacesailor24** [comment]
Hey @trmrtn, just curious what your use case is for not wanting to provide an ACC? By not providing an ACC (or an always true one as I suggested above) then anyone is allowed to obtain the decryption shares, regardless of the provided AuthSig

If you were looking to gatekeep access based on a list of authorized identifiers e.g. addresses, you could do something [like this](https://developer.litprotocol.com/v3/sdk/access-control/evm/basic-examples#a-specific-wallet-address)

**Comment by spacesailor24** [comment]
@trmrtn Your use case makes sense to me! And I agree, it seems like your ACC should interact with some sort of allow list where the user identifier is being forwarded from the service provider

I'm checking with the devs regarding your questions to make sure I don't provide incorrect info, so will get back to you when I have answers!

Also thank you for getting back to me, and thank you for the additional questions!

**Comment by spacesailor24** [comment]
@trmrtn Still working on getting an answer to 1.

---

Capacity credits are actually only required for decryption, because that's the only time Lit nodes are asked to do work.

For encryption:

Further depicted in [the docs](https://developer.litprotocol.com/v3/sdk/access-control/encryption), the encryption process flows:

1. Generate an AuthSig
2. Create an ACC
3. Use the hash of the ACC and the hash of the `dataToEncrypt` to create a identity parameter
    - This is handled for you by the Lit SDK when using `encryptString` or similar
4. Encrypt `dataToEncrypt` using the network's public BLS key locally and the created identity parameter

All of the above steps are performed locally with no requests to Lit nodes

Then for decryption:

1. Obtain the ciphertext and encryption metadata
    - Important to note that Lit does **not** handle the storage of the ciphertext or the metadata generated from encryption on your behalf, you're expected to make this data available for decryption
    - Encryption metadata includes:
        - ACC
        - hash of `dataToEncrypt`
2. Generate/obtain the AuthSig
3. Use Lit SDK (e.g. `decryptString`) to decrypt ciphertext
    - This step does submit a request to the Lit nodes to perform the decryption and requires capacity credits

```typescript
async decrypt(ciphertext: string, dataToEncryptHash: string, accessControlConditions: any) {
  if (!this.litNodeClient) {
    await this.connect()
  }

  const authSig = await LitJsSdk.checkAndSignAuthMessage({ chain: 'ethereum' })
  const decryptedString = LitJsSdk.decryptToString(
    {
      accessControlConditions,
      ciphertext,
      dataToEncryptHash,
      authSig,
      chain: 'ethereum',
    },
    litNodeClient,
  );
  return { decryptedString }
}
```

**Comment by trmrtn** [comment]
This is super clear now, appreciate it @spacesailor24 !
