### ISSUE TITLE
Questions related to PKPs, Contracts and Nodes

### ISSUE THREAD

**Issue by spacesailor24** [LIT-Protocol/Issues-and-Reports#16]
### Description of the issue

[From Discord](https://discord.com/channels/896185694857343026/1230182783071027260/1230182783071027260):

Hi. I did a deep dive into the Lit Protocol codebase (contracts, js-sdk, relay server, etc..) while doing some testing and prototyping using PKPs and Lit Actions. I have quite a few questions, so I will do my best to be as concise as possible. I greatly appreciate your help and time answering my questions, thank you.

1. Relay server has an option for claiming keys and calls the pkpHelper.claimAndMintNextAndAddAuthMethods method (https://github.com/LIT-Protocol/relay-server/blob/699e07c35e828c615c03c5b9abcc68c7d7835424/lit.ts#L403). I was unable to locate the aforementioned method in the contracts repository. Is there an alternative resource available somewhere, or are you developing the new version of contracts in private ?
2. What is the difference between mintNextAndAddAuthMethods and claimAndMintNextAndAddAuthMethods and what would be a case to use one over the other? If I understand correctly, both methods mint a new PKPNFT and add the provided authMethods to it. So either way, we need to wait for the NFT to be minted (the transaction to be mined), before we know the public key (and corresponding address) of the NFT, before we can proceed and send funds to it from another account.
3. If I understand correctly, to be able to mint a PKP, it first needs to be added (pushed to the stack) by the routing contract. This means that only the public keys which can be derived from the private keys distributed (and split) across the network will be added. Who has the permissions to add the public keys, the validators? 
4. Related to the previous question. Is there an interval how often public keys are added (pushed to the stack) or is there another mechanism behind this that governs this process?
5.  If we want to implement custom authentication and authorization, let's say using GitHub OAuth, would the following be the correct course of actions:
```
1. Write a Lit Action which verifies the GitHub access token and in case this step is successful, calls LitAction.signEcdsa({...}).
2. The PKPs we mint for users would then only have 1 authMethod, which would be the Hash (CID) of the deployed Lit action.
3. Now users can sign using their new PKPs through the action, by providing a valid GitHub access token.
```
6. How do the Lit Nodes and Lit Actions check if a user has permission to sign using the provided pkpPublicKey?  In case our Auth Method is a Lit Action, do the Lit Nodes only check if the calling action matches the authorized Hash (CID)?
What about if the Auth Method is an Ethereum address, how is the check done then?
7. What are the limitations of Lit Actions and which libraries are available/injected in the runtime? I found out that the execution time limit is 60s and the code size limit is 1 Mb. I also found that buffer, node:crypto and ethers libraries are available, anything else?
8. Probably related to the previous question. Where is this jwt object coming from in this lit action (https://github.com/LIT-Protocol/sign-in-with-google-lit-action/blob/310c264a6128c3189d22208ac5df919acd4f9cef/src/pages/index.tsx#L159)
9. Last question. Did the Lit Smart contracts (PKPNFT, PKPPermissions, PKPHelper,...) go through a security audit yet and is there a rough roadmap for a production ready (non beta) release of the network (mainnet) and contracts?

**Comment by spacesailor24** [comment]
1. [Link](https://github.com/LIT-Protocol/lit-assets/blob/develop/blockchain/contracts/contracts/lit-node/PKPHelper.sol#L367)

**Comment by spacesailor24** [comment]
A response from the devs:

2. Mint and claim are different as minting is generating a pkp from a random seed value and adding the auth methods specified. For claiming this seed value is provided with a signature from each node that processed it and then routed on chain with a pre determined id for that key which allows for a deterministic public key as this feature uses hierarchical key derivation under the hood.

3. Yes we use derived keys in our system for pkps, so as you described, the pkp router contract holds the context for each pkp such that our nodes can look up the pre seed and derive the key at time of request. 

4. They are pushed when `mintNext` or any other `mint` method is called on our `PKPNFT` contract.

6. We have a concept of permission scopes which are currently either sign anything or sign only personal messages (auth signature). These are registered to each auth method when added to a pkp and checked on our nodes when a request is sent to use a given pkp.

7. This is a bit vague but we use Demo as our runtime so any module that supports esm and is browser compatible should work in our runtime. So any package written only for node will have compatibility issues. 

9. Yes it has gone through audit.

**Comment by martines3000** [comment]
Thanks for the help, much appreciated. Feel free to close the issue now, as most of it was answered. I also looked at the Lit-Node code and understand the things more clearly now. 🚀 💯

**Comment by spacesailor24** [comment]
Awesome to hear, thank you @martines3000! Please don't hesitate to ask if any other questions pop up on your end 🙂
