### ISSUE TITLE
Question regarding Social logins (auth methods)

### ISSUE THREAD

**Issue by martines3000** [LIT-Protocol/Issues-and-Reports#20]
### Description of the issue

Hi. Looking at the documentation and lit-node code I see that Lit Protocol supports Google, Apple and Discord social logins as auth methods for PKPs.

If I understood correctly, Google and Apple Social logins are implemented using OpenID Connect, where the JWTs are verified using the corresponding public keys from the providers (Google, Apple) and then the `user_id` and `app_id` are extracted from them.

Discord on the other hand, is implemented using OAuth2, and the provided `access_token` is used to make a call to the `https://discord.com/api/oauth2/@me` endpoint, which responds with the authenticated user's information. This information contains both the `user_id` and `app_id` where the user authenticated.

I looked at the code found [here](https://github.com/LIT-Protocol/Node/tree/main/rust/lit-node/src/pkp/auth).

Do you think GitHub social login as a GitHub App would be possible?

**Comment by glitch003** [comment]
hi, yes, we can def support github auth.  this is a planned feature but realistically i think it will take a month or more to get it deployed onto the mainnet.  it could be on the testnet a lot sooner though.  it's also possible to implement a Lit Action that does github auth, and then use that Lit Action as the auth method on your PKP, which would let you use github auth before we implement it.  

the lit action would use fetch() and send the user's github token to the oauth /me endpoint to authenticate the user, and then check that the user is permitted to sign with that auth method (meaning, that the auth method exists on the PKPPermissions contract as a valid auth method for that PKP)

happy to provide more info here if this is interesting.  there's some more info about implementing custom auth on lit here: https://developer.litprotocol.com/v3/sdk/wallets/auth-methods/custom-auth

**Comment by martines3000** [comment]
Thanks for the answer.
