### ISSUE TITLE
[Charli] @lit-protocol/contracts-sdk fails to import cid module from multiformats package

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/Issues-and-Reports#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

^5.0.0

### Lit Network

cayenne

### Description of the bug/issue

I am encountering an issue when using the` @lit-protocol/contracts-sdk` package in my project. It appears that the package is attempting to import the `cid` module from the `multiformats` package, but it fails with the following error:
`Copy codeModule not found: Package path ./cid is not exported from package /path/to/node_modules/multiformats (see exports field in /path/to/node_modules/multiformats/package.json)
`

I have ensured that I have the latest version of both `@lit-protocol/contracts-sdk` and `multiformats` packages installed. However, I don't use the `cid` package directly in my code; it seems to be a dependency used internally by `@lit-protocol/contracts-sdk`.

### Severity of the bug

High. Can't build

### Steps To Reproduce

Install the `@lit-protocol/contracts-sdk` package and its peer dependencies.
Import and use the `@lit-protocol/contracts-sdk` package in your code.
Build or run the project.

### Anything else?

Expected Behavior:
The `@lit-protocol/contracts-sdk` package should be able to properly import and use the `cid` module from the `multiformats` package, and the project should build and run without any module resolution errors.

Environment: 
`Node.js` version: v18.19.0
`@lit-protocol/contracts-sdk` version: 5.0.0
`multiformats` version: 13.1.0

I have confirmed that the issue is not related to my project setup, as I don't use the `cid` package directly.

**Comment by zach-is-my-name** [comment]
Again I switched to bun instead of npm and I compiled successfully.  So for the false alarm

**Comment by Ansonhkg** [comment]
https://github.com/LIT-Protocol/js-sdk/pull/467
