### ISSUE TITLE
[Discord] Unable to mint Capacity Credits via the Lit Explorer

### ISSUE THREAD

**Issue by spacesailor24** [LIT-Protocol/Issues-and-Reports#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

N/A, but whatever Lit Explorer is using

### Lit Network

`habanero`

### Description of the bug/issue

I'm trying to mint capacity credits from https://explorer.litprotocol.com/get-credits and no matter what I enter for requests per kilosecond and expiration date, it says "Minting..." and the loading bar gets stuck at 50%. Here are screenshots of the browser console

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/20375610/e365118f-7603-4922-b09d-6001818481bf)
![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/20375610/989533bc-6b1f-4350-8f25-6f019496efe9)

### Severity of the bug

Blocking the creation of Capacity Credits

### Steps To Reproduce

I assume just going through the minting flow, but I tried it and it works:

<img width="1038" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/20375610/7de450f2-21fc-4aff-b6c0-be1fa01f9d1d">

**Comment by robyn3choi** [comment]
I was able to mint after quitting and reopening my browser (google chrome).
