### ISSUE TITLE
[Charli] Unexpected behavior: Session Sigs TTL is only 5 mins.

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/Issues-and-Reports#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

^5.0.0

### Lit Network

cayenne

### Description of the bug/issue

The nodes are returning to me session sigs with a time to live of only 5 minutes despite me setting (I think) an expiration time of 1 week.

![Screenshot from 2024-05-01 20-58-23](https://uploads.linear.app/d4b33f5f-8fa9-4719-893b-7305458eafa3/d1d4a919-f6ee-451f-b430-19bea9108684/b92b2674-86d0-4d1d-bfdb-25836f3dd08a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Q0YjMzZjVmLThmYTktNDcxOS04OTNiLTczMDU0NThlYWZhMy9kMWQ0YTkxOS1mNmVlLTQ1MWYtYjQzMC0xOWJlYTkxMDg2ODQvYjkyYjI2NzQtODZkMC00ZDFkLWJmZGItMjU4MzZmM2RkMDhhIiwiaWF0IjoxNzE0NjUyMTc2LCJleHAiOjMzMjg1MjEyMTc2fQ.PcP5pTX2jnK6S2i1ekR6RZ0heSbN6sltiXC0E-7BOUE)

### Severity of the bug

High

### Steps To Reproduce

1. log sessionSigs in [https://github.com/LIT-Protocol/lit-pkp-auth-demo/blob/main/src/hooks/useSession.ts](https://github.com/LIT-Protocol/lit-pkp-auth-demo/blob/main/src/hooks/useSession.ts)
2. run [https://github.com/LIT-Protocol/lit-pkp-auth-demo](https://github.com/LIT-Protocol/lit-pkp-auth-demo)
3. verify the session sigs expiration is 5 minutes by comparing "IssuedAt" date with "Expiration" in the "signedMessage" portion of the sessionSigs

### Link to code

[https://github.com/LIT-Protocol/lit-pkp-auth-demo](https://github.com/LIT-Protocol/lit-pkp-auth-demo)

### Anything else?

I'm curious if this code is related to the unexpected expiration time of 5 mins (and if so why it's overriding provider.getSessionSigs({sessionSigsParams: {expiration}}) ):

**lit-node-client/src/lib/lit-node-client-nodejs.js:1769**

```
// ===== AFTER we have Valid Signed Session Key =====
            // - Let's sign the resources with the session key
            // - 5 minutes is the default expiration for a session signature
            // - Because we can generate a new session sig every time the user wants to access a resource without prompting them to sign with their wallet
            const sessionExpiration = new Date(Date.now() + 1000 * 60 * 5);
            const capabilities = 
params.capacityDelegationAuthSig
```

**Comment by joshLong145** [comment]
@zach-is-my-name 
It looks like you are using the `getSessionSigs` implementation in  one of our `Auth Provider` Going to triage this as investigation. Will respond once we can look into it a bit.

**Comment by zach-is-my-name** [comment]
Thanks @joshLong145! Please note I've updated the Steps to Reproduce to simply logging sessionSigs from the PKP Auth Demo https://github.com/LIT-Protocol/lit-pkp-auth-demo/blob/main/src/hooks/useSession.ts

**Comment by joshLong145** [comment]
> Thanks @joshLong145! Please note I've updated the Steps to Reproduce to simply logging sessionSigs from the PKP Auth Demo https://github.com/LIT-Protocol/lit-pkp-auth-demo/blob/main/src/hooks/useSession.ts
> 
> `{"sessionKey":"aaf7535bed06e7c2f8596d812fcd812989324f99d39a8c755e954ba9b61d3afe","resourceAbilityRequests":[{"resource":{"resource":"*","resourcePrefix":"lit-litaction"},"ability":"pkp-signing"}],"capabilities":[{"sig":"0xb2434a029486dbc4220bee01be9a11cf50c659ac930ea865b306db01535defbf2cf5e3cf37eb3b95a537b7502afdc68c72f59a223b08c84ff1ab39ec00ec91ea1b","derivedVia":"web3.eth.personal.sign via Lit PKP","signedMessage":"localhost:3000 wants you to sign in with your Ethereum account:\n0x602592331a19255E5ef863211d836BEa367aCDF6\n\nLit Protocol PKP session signature I further authorize the stated URI to perform the following actions on my behalf: (1) '*': '*' for 'lit-litaction://*'.\n\nURI: lit:session:aaf7535bed06e7c2f8596d812fcd812989324f99d39a8c755e954ba9b61d3afe\nVersion: 1\nChain ID: 1\nNonce: 0x3295222bdf6816a063400c9f4f8aaa507bcd83ad37012c950089e7195c98491c\nIssued At: 2024-05-02T15:16:35Z\nExpiration Time: 2024-05-09T15:16:43.594Z\nResources:\n- urn:recap:eyJhdHQiOnsibGl0LWxpdGFjdGlvbjovLyoiOnsiKi8qIjpbe31dfX0sInByZiI6W119","address":"0x602592331a19255E5ef863211d836BEa367aCDF6"}],"issuedAt":"2024-05-02T15:16:46.482Z","expiration":"2024-05-02T15:21:46.482Z","nodeAddress":"https://cayenne.litgateway.com:7372"}`
> 
> ```
> #(ddiff == datediff)
> 
> [~/Github/pkp-social-auth-example]$ ddiff 2024-05-02T15:16:46.482Z 2024-05-02T15:21:46.482Z -f %M
> 5
> ```
> 
> ![Screenshot from 2024-05-02 11-27-26](https://private-user-images.githubusercontent.com/16063092/327506239-639f15d5-f951-48b1-9e38-beaa0b8d40d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTc1MTEsIm5iZiI6MTcxNTAxNzIxMSwicGF0aCI6Ii8xNjA2MzA5Mi8zMjc1MDYyMzktNjM5ZjE1ZDUtZjk1MS00OGIxLTllMzgtYmVhYTBiOGQ0MGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE3NDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MjZjMDAxODgwYjFiYjg3MjI4NGUyMDdlOGVjMzc0M2ZjNmZjNGU2OGFmNGY2ZDhkMjhhNjFlNjgwYWQ2ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cCj2c0y464hOR45_uEALQgWr0i7TIpF1HUvfuSZFkBc)

Thanks @zach-is-my-name 
This is quite helpful, I've added this as a high priority bug in our current tasks. Will ping this thread when it is ready.
