### ISSUE TITLE
[Beam] Lit Action condition unexpected error

### ISSUE THREAD

**Issue by carlosfebres** [LIT-Protocol/Issues-and-Reports#30]
### Description of the issue

Hi team! I've been working on creating a [Lit Action Condition](https://developer.litprotocol.com/v3/sdk/access-control/lit-action-conditions) to validate a signature from Farcaster and encrypt/decrypt a message. When I run the Lit action I get an error without details. I think you can get more details using that internal id, could you share them with me please?

```
 [ERROR] [core] [id: 575a4f512e82b] Something went wrong, internal id for request: lit_575a4f512e82b. Please provide this identifier with any support requests. Error is Rate limit exceeded.  Try again at 2024-05-04T08:21:19.138665314+00:00 - undefined
```

**Comment by bertrandbuild** [comment]
same issue here (habanero network), I could make it work by switching to the `cayenne` network for tests.

I also had to update the toSign jsParams : 
`toSign: ethers.utils.arrayify(ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Hello world"))),`
