### ISSUE TITLE
[TalentLayer] can't use contracts-sdk with react/vite

### ISSUE THREAD

**Issue by bertrandbuild** [LIT-Protocol/Issues-and-Reports#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

4.2.1 / 5.0.0

### Lit Network

habanero

### Description of the bug/issue

the `vite` command fail with the error : 

```
✘ [ERROR] No known conditions for "./cid" specifier in "multiformats" package [plugin vite:dep-pre-bundle]

    node_modules/@lit-protocol/contracts-sdk/src/lib/contracts-sdk.js:33:18:
      33 │     CID = require('multiformats/cid');      
```

### Severity of the bug

medium

### Steps To Reproduce

- `pnpm create vite` (choose React / TS + swc)
- `pnpm install ethers @lit-protocol/lit-node-client @lit-protocol/contracts-sdk @lit-protocol/lit-auth-client`
- `pnpm run dev`

(tried with yarn too)

### Anything else?

The require is not supported with the vite default config, I'm looking for a way to support it (tried with `vite-plugin-require` & `vite-require` but same error). Also tried with : 
- `rm node_modules/multiformats`
- `yarn add multiformats@9.9.0`

**Comment by zach-is-my-name** [comment]
I got mine working by either switching package managers or removing multiformats, siwe, and cid from my package.json.  But you can see I'd been struggling with this previously myself. 
https://github.com/LIT-Protocol/Issues-and-Reports/issues/22#issue-2266585884

**Comment by bertrandbuild** [comment]
oh thx @zach-is-my-name for pointing your issue 🙏 I guess I forgot to search in closed issues.
Indeed, bun is working ! I could also make it work with a basic parcel setup. 

I can see that you closed your issue but I guess that other developers will face the same troubles.
Maybe just update the doc and the readme of the @lit-protocol/contracts-sdk as a quick fix to let the team fix it ?

**Comment by zach-is-my-name** [comment]
> I can see that you closed your issue but I guess that other developers will face the same troubles.

Glad that helped on your end.  I'm really not confident enough in my own ability to discern my own user errors from package errors when it comes to module resolution so I closed mine. (perhaps pre-maturely).  But glad you were able to confirm it for me. I think this exists as well:
https://github.com/LIT-Protocol/js-sdk/issues/449#issue-2270055644

**Comment by bertrandbuild** [comment]
Same here, I'm not really sure if this should be fixed by the Lit's team or the dev using vite. 

I added a quick edit in the [documentation here](https://github.com/LIT-Protocol/docs/pull/278), it's nothing much but it may help a futur dev and the team.

Let's see what's the team answer, maybe they will provide us guidance on this

**Comment by zach-is-my-name** [comment]
Yes I saw it. Very proactive.  I'm sure they'll appreciate the initiative

**Comment by Ansonhkg** [comment]
Hey sorry for the delay @bertrandbuild @zach-is-my-name, it's been a few hectic weeks to prepare for 6.0. 

I'm looking into this issue now, but I'm unable to reproduce it. Here's a [demo](https://github.com/LIT-Protocol/js-sdk-manual-tests/tree/main/vite-react-lit-5.0-issue-31-contracts-sdk) that I set up.

When I run `go()` which contains the `LitContracts` instance, I'm able to use it to mint a pkp:
<img width="1016" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/4049673/804a8459-acc6-4004-84f0-67e822ac8f6c">

Here's the vite config that I use:
https://github.com/LIT-Protocol/js-sdk-manual-tests/blob/main/vite-react-lit-5.0-issue-31-contracts-sdk/vite.config.ts

Would you be able to setup a repo that I could easily clone it to test it?

**Comment by zach-is-my-name** [comment]
I already overcame it by switching to Bun (hoisting?) but I’m sure this
will prevent a lot of grief for others who are coming with p/npm. Thanks!
