### ISSUE TITLE
[Charli] Feat Req: Detailed Network Health Dashboard 

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/Issues-and-Reports#33]
### Description of the feature request

A network status service for each Lit Network which effectively communicates if various SDK operations are runnable.     

### Use case for the feature

Would solve communication problems like these where users need to poll the administrators through informal channels to determine if it's their code’s fault that an operation won't run or the result of a Network Error.     
https://discord.com/channels/896185694857343026/916383984206889013/1237489705348759553

https://discord.com/channels/896185694857343026/986025330437410887/1235684870970413167

### Proposed solution

The kernal for this feature request exists here https://cayenne-status.litprotocol.com/ though it doesn't report enough to be helpful to users encountering errors like this:
{
    "errorKind": "Unexpected",
    "errorCode": "NodeUnknownError",
    "status": 400,
    "message": "Unknown error occured",
    "correlationId": "lit_29418b7118082",
    "details": [
        "unexpected error: ECDSA signing failed: unexpected error: unexpected error: Could not process presign: unexpected error: Unable to execute presignature: unexpected error: Error poking protocol: assertion failed received incorrect shares of kd"
    ]
}.

Ideally the service would run the various Lit SDK functions on a cron job and augment the existing Node: Up or Down with 
Node Can Return Session Sigs, Node Can Run Lit Action etc.

**Comment by spacesailor24** [comment]
So this is actually something that is already planned for internal use, but now there's a discussion about how to make it public facing, so this is in the works!

**Comment by zach-is-my-name** [comment]
Fantastic! Once again I’m happy to close if it’s something already tracked internally. Thanks for being a catalyst on this!
