### ISSUE TITLE
No wallets installed or provided

### ISSUE THREAD

**Issue by rot0505** [LIT-Protocol/Issues-and-Reports#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

5.0.0

### Lit Network

cayenne

### Description of the bug/issue

I am building chrome extension using the following stacks
- Vite + React
- Lit protocol to secure password.
- @rainbow-me/rainbowkit to connect wallet

I am building chrome extension, so I connect my mobile wallet to scan QR code. I connect wallet exactly and got the address.
but when I try to encrypt password using lit protocol, I got error message: "No wallets installed or provided"

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/86523551/1507747c-1a1b-4c92-bf0d-08e47a908a05)

### Severity of the bug

I can't build chrome extension app using lit protocol.

there are web & extension version. It's working in web but not working in extension. In extension, I connected mobile wallet to scan QR code.

### Steps To Reproduce

1. I am building chrome extension using Vite and React.
2. I am using @rainbow-me/rainbowkit wallet connector
3. In chrome extension, I am connected mobile wallet to scan QR code. and I can get wallet address.
4. But when I try to call Lit protocol. I got this issue. "No wallets installed or provided"
![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/86523551/8c6d71c1-2e86-4201-a23d-6be31605cf39)

### Link to code

Here is my encrypt code in Lit class.

 ```
async encrypt(data: string) {
    const litNodeClient = new LitNodeClient({
      alertWhenUnauthorized: false,
      litNetwork: "cayenne",
    });
    await litNodeClient.connect();
    const chain = "ethereum";
    let nonce = litNodeClient.getLatestBlockhash();

    const authSig = await checkAndSignAuthMessage({  // I think there is bug in this part.
      chain: "ethereum",
      nonce,
    });

    const accessControlConditions = [
      {
        contractAddress: "",
        standardContractType: "",
        chain: "ethereum",
        method: "eth_getBalance",
        parameters: [":userAddress", "latest"],
        returnValueTest: {
          comparator: ">=",
          value: "0", // 0 ETH
        },
      },
    ];

    const { ciphertext, dataToEncryptHash } = await encryptString(
      {
        accessControlConditions,
        authSig,
        chain,
        dataToEncrypt: data,
      },
      litNodeClient
    );

    return { ciphertext, dataToEncryptHash };
  }
```

**Comment by spacesailor24** [comment]
If you're using Wallet connect, have you tried passing `walletConnectProjectId` to `checkAndSignAuthMessage`?

**Comment by spacesailor24** [comment]
Speaking with the SDK team, using wallet connect won't work with `checkAndSignAuthMessage`, I'm trying to check if there's an alternative for you to use

**Comment by rot0505** [comment]
I am using mobile meta mask

**Comment by spacesailor24** [comment]
But you're using Wallet Connect under the hood within your browser extension to connect to the metamask wallet?

**Comment by rot0505** [comment]
I am not using WalletConnect mobile wallet. I am using metamask mobile app to scan the above QR code.

Once I add `walletConnectProjectId` to `checkAndSignAuthMessage`, I got another result.
![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/86523551/cb4a2613-c127-4a30-8aff-7b54e028fabf)

**Comment by spacesailor24** [comment]
Oh sorry about that, I misread what you said<br><br>So you're

* using `@rainbow-me/rainbowkit`'s wallet connector
* selecting MetaMask mobile wallet
* the QR code pops up
* you scan it with your mobile device
* the ETH address pops up in your browser extension
* then you try to encrypt data with Lit and are getting the error?

**Comment by rot0505** [comment]
Correct

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/86523551/a2503475-7a5e-478a-838c-0efffc99bc40)

**Comment by rot0505** [comment]
And here is error message I can see in dev console.

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/86523551/7cc9954e-1fb5-468c-96cc-0ec05935df68)

**Comment by rot0505** [comment]
And here is error message in dev console

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/86523551/f986de01-7235-4d24-9db3-9dca9d896d51)
![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/86523551/a199d4ca-72ae-48e9-9504-b6196c1c9b9f)

**Comment by spacesailor24** [comment]
One of our SDK devs mentioned that the SDK may not be optimized enough to run inside a chrome extension yet due to it's bundle size. Also the compatibility with rainbowkit hasn't been confirmed, but is a goal of the SDK to support

He also mentioned that if you're able to get the signer function out of rainbowkit (after connecting your MM wallet), you can use it to manually create a SIWE message and sign it ([doc example](https://developer.litprotocol.com/v3/sdk/authentication/auth-sig#obtaining-an-authsig-on-the-server-side)) instead of using `checkAndSignAuthMessage`which seems to be the cause of your error

**Comment by rot0505** [comment]
SDK is working with rainbowkit correctly. I've checked it works correctly in web version.

Okay, I will check it.

**Comment by spacesailor24** [comment]
> SDK is working with rainbowkit correctly. I've checked it works correctly in web version.

That's great to hear, it might just be related to running it within a browser extension. The SDK does use WASM and the error messages you're getting seem to suggest a lack of support when executing within the extension

**Comment by rot0505** [comment]
>He also mentioned that if you're able to get the signer function out of rainbowkit (after connecting your MM wallet), you can use it to manually create a SIWE message and sign it (doc example) instead of using checkAndSignAuthMessagewhich seems to be the cause of your error

But the problem is I wanna use mobile wallet to connect to scan QR in chrome extension. I don't wanna connect browser extension in my extension.

**Comment by joshLong145** [comment]
@rot0505 
From the looks of your error it seems that there is a block on our WASM module being loaded in your environment. And perhaps a block on some arbitrary code execution looking at some of the errors in your screen shot more closely. Would it be possible to instead get a `ethers.Signer` from your wallet connect separately. as @spacesailor24 suggested?  
There might not be a current work around for the lack of WebAssembly support within your browser extension as I am not sure what kind of api's an extension is given access to.
