### ISSUE TITLE
[Lit Protocol] Getting clock error when trying to sign JWT

### ISSUE THREAD

**Issue by serdave-eth** [LIT-Protocol/Issues-and-Reports#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

6.0.2

### Lit Network

Cayenne

### Description of the bug/issue

I am trying to generate a signed JWT. I was able to connect to the network and generate session sigs, but when I run this command:
const jwt = await litNodeClient.getSignedToken({
                accessControlConditions,
                chain: 'ethereum',
                sessionSigs,
              });

I keep getting the attached error. I checked and my computer clock seems to be accurate.
<img width="552" alt="LIT ERROR" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/109369256/5e7a1400-c626-438d-844a-23c53f85bc4c">

### Severity of the bug

High severity. I am not able to continue integrating Lit Protocol into my project because of this bug.

### Steps To Reproduce

1. Download linked repo
2. Change line 37 in app/page.tsx to the wallet address you want to test with
3. Run "npm run build" and "npm start"
4. Open http://localhost:3000/ in your browser
5. Click "Check Access"
6. Follow the steps of connecting your wallet and signing the message
7. In the developer tools console you will see the error

### Link to code

https://github.com/serdave-eth/livepeer-grant-sandbox

### Anything else?

I checked that I was able to generate the session sigs correctly. I also basically copied and pasted the functions for generating session sigs and signing JWT from this repo:
https://github.com/LIT-Protocol/developer-guides-code/tree/master/conditional-signing

**Comment by spacesailor24** [comment]
Hi there, thank you for opening an issue and providing reproduction steps! Your ticket is now in our triage queue and we will be investigating this shortly
