### ISSUE TITLE
[DEVS] Cannot create a SessionSig using a provider (Lit Relayer approach)

### ISSUE THREAD

**Issue by capitaharlock** [LIT-Protocol/Issues-and-Reports#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

6

### Lit Network

manzano

### Description of the bug/issue

**Purpose:**
We aim to establish a process where an "End user" creates a password and is then shown a private key. From that point onward, we will manage this wallet without any further action required from the End user.

<img width="1079" alt="diagram" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/7f8ba860-53ec-40a3-b897-290ba2880c26">

**Problem:**
"// Generate session signatures" snipet is not working.
I am sure one problem is the "authMethod". Looks like this is expecting the authMethod Object instance, but I dont know how to get it, and its also confusing: provider was instantiated using an auth method, but I can't find it in properties or methods list.

**Code:**

```
import { ethers } from 'ethers';
import { WebAuthnProvider, LitAuthClient, BaseProvider } from '@lit-protocol/lit-auth-client';
import { LitNodeClient } from '@lit-protocol/lit-node-client';
import { IRelayPKP,SessionSigs } from '@lit-protocol/types';
import { ProviderType } from '@lit-protocol/constants';
import { LitAbility, LitActionResource } from '@lit-protocol/auth-helpers';
import { LitRelayerAddUser } from '@/lib/lit/litRelayer';

const RELAYER_LIT_API = process.env.NEXT_PUBLIC_RELAYER_LIT_API;

export async function createLitWallet(): Promise<{
  userWalletAddress: string;
  newPKP: IRelayPKP;
  sessionSigs: SessionSigs;
}> {

    // Create user's Ethereum wallet
    const userWallet = ethers.Wallet.createRandom();

    // Add user to relayer
    await LitRelayerAddUser([userWallet.address]);

    // Initialize LitNodeClient
    const litNodeClient: LitNodeClient = new LitNodeClient({
      alertWhenUnauthorized: false,
      litNetwork: 'manzano',
      debug: true,
    });

    // Initialize LitAuthClient
    const litAuthClient: LitAuthClient = new LitAuthClient({
      litRelayConfig: {
        relayApiKey: RELAYER_LIT_API,
        debug: true,
      },
      litNodeClient,
    });

    // Initialize WebAuthn provider
    const provider: BaseProvider = litAuthClient.initProvider<WebAuthnProvider>(
      ProviderType.WebAuthn
    );

    // Register new WebAuthn credential and mint PKP
    const options = await provider.register();
    const txHash = await provider.verifyAndMintPKPThroughRelayer(options);
    const response = await provider.relay.pollRequestUntilTerminalState(txHash);

    if (response.status !== 'Succeeded') {
      throw new Error('PKP minting failed');
    }

    // Set new PKP
    const newPKP: IRelayPKP = {
      tokenId: response.pkpTokenId,
      publicKey: response.pkpPublicKey,
      ethAddress: response.pkpEthAddress,
    };

    // Generate session signatures
    const sessionSigs = await provider.getSessionSigs({
      pkpPublicKey: String(newPKP.publicKey),
      authMethod: provider.getAuthMethodId,
      sessionSigsParams: {
        resourceAbilityRequests: [{
          resource: new LitActionResource('*'),
          ability: LitAbility.PKPSigning,
        }],
      },
      LitNodeClient: litNodeClient
    });

    return {
      userWalletAddress: userWallet.address,
      newPKP,
      sessionSigs,
    };

}
```

**More information:**
I've tried 2 approaches:

1 Using an authenticated provider:
The code pasted here.

2 Using server side callback:
https://developer.litprotocol.com/sdk/serverless-signing/quick-start#obtaining-asession-signatureon-the-server-side
But the callback is not working
I can provide this code, but if the approach 1 is working I think is the best option.

### Severity of the bug

Well, we are totally stucked here.
Without sessions sigs we cannot move forward and work on LitActions and so on.

### Steps To Reproduce

errConstructorFunc {message: 'This usually means your JSON body is wrong. Please…lit-js-sdk/api_docs_html/index.html#litnodeclient', errorCode: 'NodeBadInput', errorKind: 'Unexpected', status: 422, details: Array(1), …}
details: ['caught rocket 422: bad input error']
errorCode: "NodeBadInput"
errorKind: "Unexpected"
message: "This usually means your JSON body is wrong. Please check that you have sent over every required JSON parameter and that the types are correct according to the docs here https://lit-protocol.github.io/lit-js-sdk/api_docs_html/index.html#litnodeclient"
requestId: "5cd37b7598e77"
status: 422
[[Prototype]]: Object

<img width="1264" alt="logs" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/a69afd3c-e42f-4c7f-9e14-bd1132d7d58a">

### Anything else?

Just ask me if you need more. Thanks in advance !

**Comment by capitaharlock** [comment]
Hi, any chance to take a look on this ?

**Comment by awisniew207** [comment]
Hello!<br><br>The error seems to be with authMethod, an invalid data error, meaning the datatype is probably incorrect. The method you are using in provider.getSessionSigs, [getAuthMethodId](https://lit-js-sdk-v3-api-docs.vercel.app/classes/lit_auth_client_src.BaseProvider.html#getAuthMethodId), will take an AuthMethod datatype and return the id as a string. However, the authMethod property in getSessionSigs actually [expects an object of type AuthMethod](https://lit-js-sdk-v3-api-docs.vercel.app/interfaces/types_src.BaseProviderSessionSigsParams.html#authMethod), not a string. <br><br>With your provider being of type WebAuthnProvider, you might try using the [authenticate](https://lit-js-sdk-v3-api-docs.vercel.app/classes/lit_auth_client_src.WebAuthnProvider.html#authenticate) method instead.<br><br>The AuthMethod datatype expected by getSessionSigs will have the format:<br>{<br> accessToken: "your access token here",<br> authMethodType: 3,

}<br><br>If you are looking for more information on AuthMethod datatypes, it can be found [here](https://v6-api-doc-lit-js-sdk.vercel.app/interfaces/types_src.AuthMethod.html). <br>A similar implementation of authMethods can be found [here](https://developer.litprotocol.com/sdk/wallets/auth-methods/custom-auth#example-setting-authentication-context-with-lit-actions). Please note that in the linked implementation, authMethods is plural, which is slightly different from yours. 

If you need additional support with this issue, please reach out!

**Comment by capitaharlock** [comment]
Thanks for your response! While waiting, I continued evolving the code in search of a solution. Sorry about that. We had a chat with the Lit Protocol staff, and I have been updating the code changes there.

I am now with EthWalletProvider and already using the authenticate method to create the AuthMethod object:
`return provider.authenticate({ address: ethersSigner.address, signMessage })`

This AuthMethod object can be used to mint PKPs, but an error occurs on the nodes when trying to get the SessionSigs.
<img width="824" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/c3a34994-6f1f-4163-89dd-442d284d50b9">

Would you mind to take a look at this one ?
Thanks !!


CODE:
`import { ethers } from "ethers"
import { LitAuthClient, EthWalletProvider } from "@/lib/external/lit-auth-client"
import { LitNodeClient } from "@/lib/external/lit-node-client"
import { AuthMethod, IRelayPKP, LIT_NETWORKS_KEYS } from "@lit-protocol/types"
import { AuthMethodScope, ProviderType } from "@lit-protocol/constants"
import { LitAbility, LitPKPResource, LitActionResource, createSiweMessageWithRecaps, generateAuthSig } from "@lit-protocol/auth-helpers"

const LIT_NETWORK: LIT_NETWORKS_KEYS = process.env.NEXT_PUBLIC_LIT_NETWORK as LIT_NETWORKS_KEYS
const RELAYER_LIT_API = process.env.NEXT_PUBLIC_RELAYER_LIT_API
const DOMAIN = process.env.NEXT_PUBLIC_DOMAIN || ""
const ORIGIN = process.env.NEXT_PUBLIC_ORIGIN || ""

interface AuthUserKeys {
    address: string
    privateKey: string
}

export async function createLitWallet(): Promise<IRelayPKP> {
    console.log("Starting createLitWallet process...")
    clearBrowserData()

    const authUserKeys = createAuthUserKeys()
    const ethersSigner = createEthersSigner(authUserKeys.privateKey)
    const { litNodeClient, litAuthClient } = await initializeLitClients()
    const provider = initializeProvider(litAuthClient)
    const authMethod = await authenticateProvider(provider, ethersSigner, litNodeClient)
    const newPKP = await mintPKP(provider, authMethod)
    const pkpSessionSigs = await createPKPSessionSigs(litNodeClient, newPKP, authMethod) //, provider, ethersSigner
    await litNodeClient.disconnect()
    return newPKP
}

function createAuthUserKeys(): AuthUserKeys {
    const randomWallet = ethers.Wallet.createRandom()
    return {
        address: randomWallet.address,
        privateKey: randomWallet.privateKey,
    }
}

function createEthersSigner(privateKey: string): ethers.Wallet {
    return new ethers.Wallet(privateKey, new ethers.providers.JsonRpcProvider("https://chain-rpc.litprotocol.com/http"))
}

async function initializeLitClients() {
    const litNodeClient = new LitNodeClient({
        alertWhenUnauthorized: false,
        litNetwork: LIT_NETWORK,
        debug: true,
    })
    await litNodeClient.connect()

    const litAuthClient = new LitAuthClient({
        litRelayConfig: {
            relayApiKey: RELAYER_LIT_API!,
            debug: true,
        },
        litNodeClient,
    })

    return { litNodeClient, litAuthClient }
}

function initializeProvider(litAuthClient: LitAuthClient): EthWalletProvider {
    if (!DOMAIN || !ORIGIN) {
        throw new Error("DOMAIN and ORIGIN must be set in environment variables")
    }
    return litAuthClient.initProvider<EthWalletProvider>(ProviderType.EthWallet, {
        domain: DOMAIN,
        origin: ORIGIN,
    })
}

async function authenticateProvider(provider: EthWalletProvider, ethersSigner: ethers.Wallet, litNodeClient: LitNodeClient): Promise<AuthMethod> {
    const signMessage = async ({ expiration, uri }) => {
        const toSign = await createSiweMessageWithRecaps({
            walletAddress: ethersSigner.address,
            nonce: await litNodeClient.getLatestBlockhash(),
            uri,
            expiration,
            resources: [
                { resource: new LitPKPResource("*"), ability: LitAbility.PKPSigning },
                { resource: new LitActionResource("*"), ability: LitAbility.LitActionExecution },
            ],
            litNodeClient,
            domain: DOMAIN,
        })
        return generateAuthSig({ signer: ethersSigner, toSign })
    }

    return provider.authenticate({ address: ethersSigner.address, signMessage })
}

async function mintPKP(provider: EthWalletProvider, authMethod: AuthMethod): Promise<IRelayPKP> {
    const options = { permittedAuthMethodScopes: [[AuthMethodScope.SignAnything]] }
    const mintTx = await provider.mintPKPThroughRelayer(authMethod, options)
    const response = await provider.relay.pollRequestUntilTerminalState(mintTx)

    if (response.status !== "Succeeded") {
        throw new Error("Minting failed")
    }

    return {
        tokenId: response.pkpTokenId,
        publicKey: response.pkpPublicKey,
        ethAddress: response.pkpEthAddress,
    }
}

async function createPKPSessionSigs(litNodeClient: LitNodeClient, newPKP: IRelayPKP, authMethod: AuthMethod) {
    const expirationTime = new Date(Date.now() + 5 * 60 * 1000) // 5 min
    return litNodeClient.getPkpSessionSigs({
        pkpPublicKey: newPKP.publicKey,
        authMethods: [authMethod],
        resourceAbilityRequests: [
            { resource: new LitPKPResource("*"), ability: LitAbility.PKPSigning },
            { resource: new LitActionResource("*"), ability: LitAbility.LitActionExecution },
        ],
        expiration: expirationTime.toISOString(),
    })
}

function clearBrowserData(): void {
    document.cookie.split(";").forEach((cookie) => {
        document.cookie = cookie.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/")
    })
    localStorage.clear()
    sessionStorage.clear()
    console.log("Browser data cleared.")
}
`

**Comment by awisniew207** [comment]
Hello again!<br><br>I think I might have found the issue. This function:

```
async function authenticateProvider(provider: EthWalletProvider, ethersSigner: ethers.Wallet, litNodeClient: LitNodeClient): Promise {
    const signMessage = async ({ expiration, uri }) => {
        const toSign = await createSiweMessageWithRecaps({
        walletAddress: ethersSigner.address,
        nonce: await litNodeClient.getLatestBlockhash(),
        uri,
        expiration,
        resources: [
        { resource: new LitPKPResource(""), ability: LitAbility.PKPSigning },
        { resource: new LitActionResource(""), ability: LitAbility.LitActionExecution },
        ],
        litNodeClient,
        domain: DOMAIN,
        })
        return generateAuthSig({ signer: ethersSigner, toSign })
    }
  return provider.authenticate({ address: ethersSigner.address, signMessage })
  }
```

The second return attempts to return type `AuthMethod` using the `authenticate` method; however, the second parameter `signMessage` is of type `AuthSig` which is not supported by `EthWalletProvider`'s `authenticate` method. I believe this could be the issue because of the parsing error received when using `getPkpSessionSigs`, considering that `AuthMethod` expects primarily strings and received a map. More on the supported parameter types can be found [here](https://v6-api-doc-lit-js-sdk.vercel.app/classes/lit_auth_client_src.EthWalletProvider.html#authenticate-2). <br><br>Please let me know if this helps! All-in-all, I would just make sure your parameters are of the correct type!

**Comment by capitaharlock** [comment]
Hello guys, I did try to test the examples on the sdk repo and I was founding the same errors.
In this case I did authenticate with google, using the demo-pkp-session-sigs code, without alteration.
It gets a SIWE error when reaching the nodes. In my other code approches I did get the same one.
At the moment, I am getting another error, mentioned in my previous comment. 

I am just sending it in case it helps to find out whats the problem in my code.
Thanks again !

![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/9f53d090-920b-4510-8357-e27db6bbefc0)
![image](https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/fbfd3b49-8041-45ba-8050-14f9925a84aa)
<img width="289" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/c0bc3b1e-1b04-45af-bc44-76e4f72d36aa">

**Comment by capitaharlock** [comment]
I don't think it can be avoided looking at the code.

If sent empty:
<img width="578" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/b71bc031-4884-4694-8d21-92ea4077f399">

If removed key:
<img width="595" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/3dbff8cc-b119-40e6-b93e-9fb8b8d51893">

I will setup a simple repo that can be just downloaded and runned so It can help you to debug.

Anyway, would it be possible to get a working example from your side ?
I mean, I just need to see a background code (nodejs) using litrelayer (to pay for gas to any wallet I add), using an Eth auth provider (so we dont need to prompt a wallet window) to be able to use the new wrapped keys feature, and obviously to run Lit actions.  I couldn't find any updated or working example around this approach.

I really appreacciate your help !
Thanks for your time

**Comment by awisniew207** [comment]
Hello!<br><br>Thank you for providing the simple repo. Using it, we debugged some issues and introduced a new function to your code to show how you could be using the new wrapped keys feature. The following code is able to implement all of the functionality you had previously, but also successfully import a private wallet address for the PKP's wrapped key, and sign a transaction using that wrapped key.<br><br>Changes made:

\-Removed the EOA_PRIVATE_KEY from the code, please replace it with a private key<br>-Set all Lit Networks to Cayenne

\-Hardcoded chain RPC URL

\-Added an expiration time of 10 minutes to `sessionSigs`

\-Added the `signTxnWithWrapped` function:

This function tests signing a transaction using your PKP's wrapped key. We first make an `EthereumLitTransaction` interface ([docs](https://developer.litprotocol.com/sdk/wrapped-keys/sign-transaction#signtransactionwithencryptedkeys-interface)), which includes the transaction to be signed by our wrapped key. We then use the `signTransactionWithEncryptedKey` function ([docs](https://developer.litprotocol.com/sdk/wrapped-keys/sign-transaction#signtransactionwithencryptedkeys-interface)) to designate the wrapped key as the signer. Please note that if you wish to broadcast your transactions with this function (`broadcast: true`), you will need to add funds to the wrapped key address as they will not be subsidized by the relayer.<br><br>Please also note that the transaction `value` is in ETH, and the `gasPrice`/`gasLimit` are in WEI.

```
import { LitNodeClient } from "@lit-protocol/lit-node-client"
import { LitNetwork, AuthMethodScope, LIT_CHAIN_RPC_URL } from "@lit-protocol/constants"
import { ethers } from "ethers"
import { LitContracts } from "@lit-protocol/contracts-sdk"
import { LitPKPResource, LitActionResource } from "@lit-protocol/auth-helpers"
import { LitAbility } from "@lit-protocol/types"
import { ipfsHelpers } from "ipfs-helpers"
import { api } from "@lit-protocol/wrapped-keys"
import { signTransactionWithEncryptedKey } from "@lit-protocol/wrapped-keys/src/lib/api"
import { EthereumLitTransaction } from "@lit-protocol/wrapped-keys/src/lib/types"

const { importPrivateKey } = api

export const EOA_PRIVATE_KEY = "" // secret :)

let globalState: any = {
    permittedAuthMethodAdded: false,
    litActionPermitted: false,
}

const saveToLocalStorage = () => {
    const dataToSave = {
        pkp: globalState.pkp,
        customAuthMethod: globalState.customAuthMethod,
        litActionCode: globalState.litActionCode,
        ipfsHash: globalState.ipfsHash,
        permittedAuthMethodAdded: globalState.permittedAuthMethodAdded,
        litActionPermitted: globalState.litActionPermitted,
    }
    localStorage.setItem("litProtocolData", JSON.stringify(dataToSave))
}

const loadFromLocalStorage = () => {
    const savedData = localStorage.getItem("litProtocolData")
    if (savedData) {
        globalState = { ...JSON.parse(savedData), ...globalState }
    }
}

export const connectLitNodeClientToCayenne = async () => {
    const litNodeClient = new LitNodeClient({
        alertWhenUnauthorized: false,
        litNetwork: LitNetwork.Cayenne,
        debug: true,
    })
    await litNodeClient.connect()
    globalState.litNodeClient = litNodeClient
}

export const connectLitContractsToCayenne = async () => {
    const litContracts = new LitContracts({
        signer: new ethers.Wallet(EOA_PRIVATE_KEY, new ethers.providers.JsonRpcProvider("https://chain-rpc.litprotocol.com/http")),
        debug: false,
        network: LitNetwork.Cayenne,
    })
    await litContracts.connect()
    globalState.litContracts = litContracts
}


export const mintPkpWithLitContracts = async () => {
    if (!globalState.pkp) {
        const eoaWalletOwnedPkp = (await globalState.litContracts.pkpNftContractUtils.write.mint()).pkp
        globalState.pkp = eoaWalletOwnedPkp
        saveToLocalStorage()
    }
}

export const createCustomAuthMethod = async () => {
    if (!globalState.customAuthMethod) {
        globalState.customAuthMethod = {
            authMethodType: 89989,
            authMethodId: "app-id-xxx:user-id-yyy",
        }
        saveToLocalStorage()
    }
}

export const addPermittedAuthMethodToPkp = async () => {
    if (!globalState.permittedAuthMethodAdded) {
        try {
            await globalState.litContracts.addPermittedAuthMethod({
                pkpTokenId: globalState.pkp.tokenId,
                authMethodType: globalState.customAuthMethod.authMethodType,
                authMethodId: globalState.customAuthMethod.authMethodId,
                authMethodScopes: [AuthMethodScope.SignAnything],
            })
            globalState.permittedAuthMethodAdded = true
            saveToLocalStorage()
        } catch (e) {
            console.error("Error adding permitted auth method to PKP:", e.message)
        }
    } else {
        console.log("Permitted auth method already added, skipping step.")
    }
}

export const createLitActionCode = async () => {
    if (!globalState.litActionCode) {
        globalState.litActionCode = `(async () => {
            const tokenId = await Lit.Actions.pubkeyToTokenId({ publicKey: pkpPublicKey });
            const permittedAuthMethods = await Lit.Actions.getPermittedAuthMethods({ tokenId });
            const isPermitted = permittedAuthMethods.some((permittedAuthMethod) => {
                if (permittedAuthMethod["auth_method_type"] === "0x15f85" && 
                    permittedAuthMethod["id"] === customAuthMethod.authMethodId) {
                return true;
                }
                return false;
            });
            LitActions.setResponse({ response: isPermitted ? "true" : "false" });
        })();`
        saveToLocalStorage()
    }
}

export const convertLitActionCodeToIpfsCid = async () => {
    if (!globalState.ipfsHash) {
        globalState.ipfsHash = await ipfsHelpers.stringToCidV0(globalState.litActionCode)
        saveToLocalStorage()
    }
}

export const permitLitActionToUsePkp = async () => {
    if (!globalState.litActionPermitted) {
        try {
            await globalState.litContracts.addPermittedAction({
                ipfsId: globalState.ipfsHash,
                pkpTokenId: globalState.pkp.tokenId,
                authMethodScopes: [AuthMethodScope.SignAnything],
            })
            globalState.litActionPermitted = true
            saveToLocalStorage()
        } catch (e) {
            console.error("Error adding permitted action to PKP:", e.message)
        }
    } else {
        console.log("Lit Action already permitted, skipping step.")
    }
}

export const getSessionSigsUsingPkpPubKeyAndCustomAuth = async () => {
    globalState.litActionSessionSigs = await globalState.litNodeClient.getLitActionSessionSigs({
        pkpPublicKey: globalState.pkp.publicKey,
        expiration: new Date(Date.now() + 1000 * 60 * 10).toISOString(), // 10 minutes
        resourceAbilityRequests: [
            { resource: new LitPKPResource("*"), ability: LitAbility.PKPSigning },
            { resource: new LitActionResource("*"), ability: LitAbility.LitActionExecution },
        ],
        litActionCode: Buffer.from(globalState.litActionCode).toString("base64"),
        jsParams: {
            pkpPublicKey: globalState.pkp.publicKey,
            customAuthMethod: {
                authMethodType: `0x${globalState.customAuthMethod.authMethodType.toString(16)}`,
                authMethodId: `0x${Buffer.from(new TextEncoder().encode(globalState.customAuthMethod.authMethodId)).toString("hex")}`,
            },
            sigName: "custom-auth-sig",
        },
    })
}

export const pkpSignWithLitActionSessionSigs = async () => {
    try {
        const res = await globalState.litNodeClient.pkpSign({
            pubKey: globalState.pkp.publicKey,
            sessionSigs: globalState.litActionSessionSigs,
            toSign: ethers.utils.arrayify(ethers.utils.keccak256([1, 2, 3, 4, 5])),
        })
        globalState.pkpSignResult = res
    } catch (e) {
        console.error("Error signing with PKP:", e.message)
    }
}

export const insertWrappedKeys = async () => {
    try {
        const wallet = ethers.Wallet.createRandom()
        const pkpAddress = await importPrivateKey({
            pkpSessionSigs: globalState.litActionSessionSigs,
            litNodeClient: globalState.litNodeClient,
            privateKey: wallet.privateKey,
            publicKey: wallet.publicKey,
            keyType: "K256",
        })
        globalState.pkpAddress = pkpAddress
        console.log("Wrapped key address", wallet.address);
    } catch (e) {
        console.error("Error in insertWrappedKeys:", e)
    }
}

export const signTxnWithWrapped = async () => {
    const unsignedTransaction: EthereumLitTransaction = {
        chain: 'chronicleTestnet',
        toAddress: '0x69c7C120Ad9B545AD744D21616b68d0A95A97D45',
        value: '0.0000000000001', // Make sure the funds are sufficient (in ETH)
        chainId: 175177, 
        //gasPrice: '20000000000', // Does not need to be set, we will estimate it within the Lit Action
        gasLimit: 21000, // Do not have to provide this either, but sometimes can cause errors if you do not
    };
    try {
        const test = await signTransactionWithEncryptedKey({
            litNodeClient: globalState.litNodeClient,
            network: 'evm',
            pkpSessionSigs: globalState.litActionSessionSigs,
            broadcast: true, // true requires wrapped key to have funds
            unsignedTransaction: unsignedTransaction
        });
        globalState.txnHash = test;
        console.log("Transaction Hash: ", globalState.txnHash);
    } catch (e) {
        console.error("Error in signMessageWithWrapped:", e)
    }
}

const stepsConfig = [
    { step: 1, action: connectLitNodeClientToCayenne, description: "Connect LitNodeClient" },
    { step: 2, action: connectLitContractsToCayenne, description: "Connect LitContracts" },
    { step: 3, action: mintPkpWithLitContracts, description: "Mint a PKP" },
    { step: 4, action: createCustomAuthMethod, description: "Create a custom auth method" },
    { step: 5, action: addPermittedAuthMethodToPkp, description: "Add Permitted Auth Method" },
    { step: 6, action: createLitActionCode, description: "Create a Lit Action code" },
    { step: 7, action: convertLitActionCodeToIpfsCid, description: "Convert Lit Action to IPFS CID" },
    { step: 8, action: permitLitActionToUsePkp, description: "Permit Lit Action" },
    { step: 9, action: getSessionSigsUsingPkpPubKeyAndCustomAuth, description: "Get Session Sigs" },
    { step: 10, action: pkpSignWithLitActionSessionSigs, description: "PKP Sign" },
    { step: 11, action: insertWrappedKeys, description: "Wrapped keys" },
    { step: 12, action: signTxnWithWrapped, description: "Transaction signed with the wrapped key" },
]

export const runAllSteps = async (useStoredData: boolean = false) => {
    if (useStoredData) {
        loadFromLocalStorage()
    } else {
        localStorage.removeItem("litProtocolData")
        globalState = {}
    }

    for (const step of stepsConfig) {
        console.log(`Executing step ${step.step}: ${step.description}`)
        await step.action()
    }
    console.log("All steps completed. Final state:", globalState)
}

// If you want to run this in a browser environment, you can use this code
if (typeof document !== "undefined") {
    document.addEventListener("DOMContentLoaded", () => {
        const freshStartButton = document.createElement("button")
        freshStartButton.textContent = "Start Fresh"
        freshStartButton.addEventListener("click", () => runAllSteps(false))
        document.body.appendChild(freshStartButton)

        const storedDataButton = document.createElement("button")
        storedDataButton.textContent = "Start with Stored Data"
        storedDataButton.addEventListener("click", () => runAllSteps(true))
        document.body.appendChild(storedDataButton)
    })
}
```

<br>This implementation worked on our end. If you have any issues executing this code, or had some different implementations in mind, [this](https://github.com/LIT-Protocol/developer-guides-code/tree/wyatt/wrapped-keys) repository has some examples of using wrapped keys, which could be used as a reference for your own implementations. Additionally, the wrapped keys [docs](https://developer.litprotocol.com/sdk/wrapped-keys/overview) provide an overview of the functions. <br><br>Also please let us know if you have any more questions! We will try our best to help!

**Comment by capitaharlock** [comment]
Hi awisniew207,
thanks for answering !

I think we are confusing threads. In your answer you're using my example code placed in the other issue:
https://github.com/LIT-Protocol/Issues-and-Reports/issues/46

This was solved on the lit-protocol side by fixing the CORS problem. The code I added to issue 46, in the github repo, is working now correctly as it is. So the wrapped keys issue is solved using the CONTRACTS approach. 

**The current problem, in this thread (44)** happens while trying to get SessionSigs using the LITRELAYER approach (using the providers from Lit SDK). And we need to work in this approach only, to be able to pay the GAS to all PKPs created by our users.

I might be wrong in my assumption, so please let me know if I am.

In case I am correct, let me set a github repo with the failing code using the litrelayer approach so you can just download and test:
[https://github.com/capitaharlock/lit-protocol-lit-relayer-approach](https://github.com/capitaharlock/lit-protocol-lit-relayer-approach)

(log in the readme)
(can be executed in node with no front)
(this code is the same that in this thread, also details can be found in screenshots as well)


**NOTE:**
According to Lit doc, we need to work in **Manzano** as a testnet right ? 
https://developer.litprotocol.com/network/migration-guide
"If you are currently in early-stage research and development, you should be using the Manzano Testnet"


Thanks a lot for your help and effort !

**Comment by awisniew207** [comment]
Hello!<br><br>Sorry for misunderstanding with my previous comment. I checked the repositories on your profile and assumed the one from July 4th was the one giving you an issue. I want to also thank you for providing the repository with the failing code for the litrelayer approach, it helped a lot with debugging.<br><br>As I mentioned in my telegram comment, the issue was in the `authenticateProvider` function, specifically the `authenticate` method. Long story short, `authenticate` would incorrectly format the `AuthSig` within the `AuthMethod`. <br><br>The below code does not use the `authenticate` method, and I was able to successfully obtain the `SessionSigs`!

```
async function authenticateProvider(provider, ethersSigner, litNodeClient) {
    const signMessage = async () => {
        const toSign = await createSiweMessageWithRecaps({
            walletAddress: ethersSigner.address,
            nonce: await litNodeClient.getLatestBlockhash(),
            resources: [
                {
                    resource: new LitPKPResource('*'),
                    ability: LitAbility.PKPSigning,
                },
                {
                    resource: new LitActionResource('*'),
                    ability: LitAbility.LitActionExecution,
                },
            ],
            litNodeClient,
            domain: DOMAIN,
        });
        const authSig = await generateAuthSig({ signer: ethersSigner, toSign });
        return authSig;
    };

    ethersSigner.signMessage = await signMessage();

    const authMethod = {
        authMethodType: 1, 
        accessToken: JSON.stringify(ethersSigner.signMessage),
    };

    return authMethod;
}
```

I did remove `expiration` and `uri` from `createSiweMessageWithRecaps`, but let me know if you would like them reimplemented. Please let me know if this works for you as well!
