### ISSUE TITLE
How to add unsupported chain

### ISSUE THREAD

**Issue by silence48** [LIT-Protocol/Issues-and-Reports#5]
### Description of the feature request

I want to be able to use access control conditions using the chain stellar.  We have rust based smart contracts and am highly knowledgeable on the capabilities of the stellar side, but it's not clear to me what I would need to do in order to add a chain that you have not yet defined.  Mind you I just started researching it today and was directed to make an issue here on github , so if i'm looking at this wrong sorry!

### Use case for the feature

I want to be able to lock content behind stellar assets, smart contract conditions, or account attributes.

### Proposed solution

Stellar has smart contracts in the form of soroban, which is a wasm vm.  Right now we have a rust sdk and assemblyscript sdk for writing the contracts.  We support SECPK and ec25519 message signing in the vm

**Comment by Aaryan-R-S** [comment]
@howard Let's assign it to someone (Here we have our first issue via the new ticketing system 🎉 )

**Comment by Aaryan-R-S** [comment]
Hey @silence48 we will get back to you on this shortly!

**Comment by Aaryan-R-S** [comment]
Hey @silence48!
We may not have that bandwidth to take upon this feature request right now. Closing this as of now!
Thanks for the feedback :)
