### ISSUE TITLE
[Discord] Resource id not found in auth_sig capabilities

### ISSUE THREAD

**Issue by spacesailor24** [LIT-Protocol/Issues-and-Reports#56]
[Discord Link](https://discord.com/channels/896185694857343026/1269078721072201781/1269078721072201781)

[Slack Thread](https://litprotocol.slack.com/archives/CB84XKFKQ/p1723135403030119?thread_ts=1723135239.901239&cid=CB84XKFKQ)

---

Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

"@lit-protocol/lit-node-client": "^6.4.0"

### Lit Network

Not provided

### Description of the bug/issue

I'm struggling to run a simple Lit Action:

Full error:

```
{
  message: 'Invalid Capability object in SIWE resource ReCap',
  errorCode: 'NodeSIWECapabilityInvalid',
  errorKind: 'Validation',
  status: 400,
  details: [
    'validation error: Resource id not found in auth_sig capabilities: validation error: Could not find valid capability.',
    'Resource id not found in auth_sig capabilities'
  ],
  requestId: 'f02f982bc3507'
}
```

Gist: [https://gist.github.com/hansy/ddd58af9f38150c86ed4837beedf6496](https://gist.github.com/hansy/ddd58af9f38150c86ed4837beedf6496)

### Severity of the bug

Blocking

### Steps To Reproduce

Gist: [https://gist.github.com/hansy/ddd58af9f38150c86ed4837beedf6496](https://gist.github.com/hansy/ddd58af9f38150c86ed4837beedf6496)

### Link to code

*No response*

### Anything else?

*No response*

**Comment by awisniew207** [comment]
Hi there!<br><br>Sorry you ran into this issue. I wasn't able to reproduce the error you were getting, but I created a working example with nearly the same code you were using. I put the example in [this branch](https://github.com/LIT-Protocol/developer-guides-code/tree/andrew/siwe-issue/session-signatures/getSessionSigs), and the working code can be tested after installing the dependencies with `yarn`, putting an `ETHEREUM_PRIVATE_KEY` in the `.env` file, and testing with `yarn test`. <br><br>Please let me know if this helps!
