### ISSUE TITLE
Decrypt within Lit Action: Using IPFS ID as an Access Control Parameter Not Working

### ISSUE THREAD

**Issue by serdave-eth** [LIT-Protocol/Issues-and-Reports#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

    "@lit-protocol/auth-helpers": "^6.4.0",
    "@lit-protocol/lit-auth-client": "^6.4.0",
    "@lit-protocol/lit-node-client": "^6.4.0",
    "@lit-protocol/types": "^6.4.0",

### Lit Network

datil-dev

### Description of the bug/issue

I am using the code from this example: https://developer.litprotocol.com/sdk/serverless-signing/combining-decryption-shares to test decrypting something within a lit action and I am getting this error:

[Lit-JS-SDK v6.4.0] [2024-08-07T22:10:42.593Z] [ERROR] [core] [id: bc8337bf4bf38] most common error: {"success":false,"error":"Uncaught (in promise) Error: Error checking access control conditions: lit_node::Error { kind: Conversion, code: NodeConditionAddressConversionError, source: lit_core::Error { kind: Conversion, msg: \"failed to decode hex from str\", source: InvalidHexCharacter { c: ':', index: 0 }, caller:  { file: \"/home/ubuntu/lit-assets/rust/lit-core/lit-core/src/utils/binary.rs:25:22\" } }, caller:  { file: \"src/access_control/mod.rs:562:21\" } }\n    at Object.decryptAndCombine (ext:lit_actions/02_litActionsSDK.js:274:14)\n    at go (<user_provided_script>:2:36)\n    at <user_provided_script>:13:1","logs":""}

Which implies that the way I'm defining the access control condition isn't correct. I'm following the guide exactly like so:
    const accessControlConditions = [
        {
          contractAddress: "",
          standardContractType: "",
          chain,
          method: "eth_getBalance",
          parameters: [":currentActionId", "latest"],
          returnValueTest: {
            comparator: "=",
            value: 'Qmd3RiHeUTgYDWU57wAEZEFcXvMcHkkJ9qZwxE1y8GoM6H',
          },
        },
      ];

And then I call the Lit action like so:
      const res = await client.executeJs({
        sessionSigs: sessionForDecryption,
        //code: genActionSource(),
        ipfsId: "Qmd3RiHeUTgYDWU57wAEZEFcXvMcHkkJ9qZwxE1y8GoM6H",
        jsParams: {
            accessControlConditions,
            ciphertext,
            dataToEncryptHash,
            authSig: authSig,
            chain
        }
      });

The Lit action works when I use this access control condition:
const accessControlConditions = [
        {
            contractAddress: '',
            standardContractType: '',
            chain,
            method: 'eth_getBalance',
            parameters: [':userAddress', 'latest'],
            returnValueTest: {
                comparator: '>=',
                value: '0',
            },
        },
    ];

### Severity of the bug

This bug is stopping me from making progress on a grant with Livepeer:

https://github.com/livepeer/grants/issues/232

### Steps To Reproduce

1. Clone this github repo: https://github.com/serdave-eth/lit-action-sandbox
2. Run npm install
3. Run npm start

### Link to code

https://github.com/serdave-eth/lit-action-sandbox

**Comment by awisniew207** [comment]
Hi there!<br><br>The breaking point here was that the `method` property inside of the `accessControlConditions` was set to `eth_getBalance`. It does say this in the docs, but this is not correct. Sorry for the oversight on our end. Correct ACCs for your use case would look more like:

```
    const accessControlConditions = [
        {
          contractAddress: '',
          standardContractType: '',
          chain: 'ethereum',
          method: '',
          parameters: [':currentActionIpfsId'],
          returnValueTest: {
            comparator: '=',
            value: "Qmd3RiHeUTgYDWU57wAEZEFcXvMcHkkJ9qZwxE1y8GoM6H",
          },
        },
      ];
```

<br>I've made a [fork of the repository](https://github.com/awisniew207/lit-action-sandbox) you provided (thank you for that, it greatly expedites debugging) with working ACCs. If you have any other questions, please let us know!

**Comment by serdave-eth** [comment]
Ah got it. Thank you! I had a feeling there was just an error in how it was documented. It's working now.
