### ISSUE TITLE
[Charli] How is gas payment handled in LitAction.runOnce()? 

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/Issues-and-Reports#58]
Hi @spacesailor24 @awisniew207
I'm looking at the example for ["Using a Single Node to Send a Transaction"](https://developer.litprotocol.com/sdk/serverless-signing/run-once#using-a-single-node-to-send-a-transaction)

It looks like a node is being asked by the Lit Action to execute the transaction with runOnce... How does the gas cost incurred by the node for executing and submitting the tx get passed on to the Lit Action (or PKP)? 

```typescript (async () => {
    const sigName = "sig1";
    // example transaction
    let txn = {
        to: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
        value: 1,
        gasPrice: 20000000000,
        nonce: 0,
    };

    // using ether's serializeTransaction
    // https://docs.ethers.org/v5/api/utils/transactions/#transactions--functions
    const serializedTx = ethers.utils.serializeTransaction(txn);
    let hash = utils.keccak256(ethers.utils.toUtf8Bytes(serializedTx));
    // encode the message into an uint8array for signing
    const toSign = await new TextEncoder().encode(hash);
    const signature = await Lit.Actions.signAndCombineEcdsa({
        toSign,
        publicKey,
        sigName,
    });

    // the code in the function given to runOnce below will only be run by one node
    let res = await Lit.Actions.runOnce({ waitForResponse: true, name: "txnSender" }, async () => {
        // get the node operator's rpc url for the 'ethereum' chain
        const rpcUrl = await Lit.Actions.getRpcUrl({ chain: "ethereum" });
        const provider = new ethers.providers.JsonRpcProvider(rpcUrl);
        const tx = await provider.sendTransaction(signature);
        return tx.blockHash; // return the tx to be broadcast to all other nodes
    });

    // set the response from the action as the result of runOnce operation
    // will be sent by all nodes, even though only a single node did the computation
    Lit.Actions.setResponse(res);
})()
`
const client = new LitNodeClient({
    litNetwork: "datil-dev",
});

await client.connect();
const res = await client.executeJs({
    code,
    sessionSigs: {} // your session
    jsParams: {
        publicKey: "<your pkp public key>",
    }
});
```

**Comment by spacesailor24** [comment]
The transaction is paid for by the PKP that's signing the transaction. In the above code, that would be corresponding ETH address for `publicKey` in:

```ts
const signature = await Lit.Actions.signAndCombineEcdsa({
        toSign,
        publicKey,
        sigName,
    });
```

The Lit node is merely forwarding the signed transaction to the blockchain network using `eth_sendRawTransaction`

**Comment by awisniew207** [comment]
FYI, that example seems to be outdated. Sorry for our oversight, we'll work on getting that changed soon. For now:<br><br>The latest properties of using `executeJs` with the `LitNodeClient` can be found [here](https://v6-api-doc-lit-js-sdk.vercel.app/interfaces/types_src.JsonExecutionSdkParams.html).<br>A more recent example of using `executeJs` can be found [here](https://github.com/LIT-Protocol/developer-guides-code/blob/master/eip-191-signing/nodejs/src/index.js#L32-L43).

**Comment by zach-is-my-name** [comment]
> The transaction is paid for by the PKP that's signing the transaction. In the above code, that would be corresponding ETH address for `publicKey` in:
> 
> ```ts
> const signature = await Lit.Actions.signAndCombineEcdsa({
>         toSign,
>         publicKey,
>         sigName,
>     });
> ```
> 
> The Lit node is merely forwarding the signed transaction to the blockchain network using `eth_sendRawTransaction`

You right. I didn't think it through.  New paradigm.  Thanks!
