### ISSUE TITLE
Need Assistance with Implementing Persistent Login Feature using Lit Protocol

### ISSUE THREAD

**Issue by gallirohik** [LIT-Protocol/Issues-and-Reports#68]
### Description of the issue

Hi Team,

I’m working on implementing the social login authentication mechanism as described in the [Lit Protocol Social login docs](https://developer.litprotocol.com/user-wallets/pkps/advanced-topics/auth-methods/social-login). I’m following the [lit-pkp-auth-demo](https://github.com/LIT-Protocol/lit-pkp-auth-demo?tab=readme-ov-file) example and have successfully set up user sign-up/login functionality.

However, I’d like to add a feature where the user remains logged in for a set period or until they manually log out. Currently, I’m not sure how to achi eve this with the existing setup.

I’ve noticed the presence of `lit-session-key` and `lit-wallet-sig` in local storage in the current implementation, but I’m unsure if they are intended to support this functionality or how they could be used for session persistence.

I've been going through the following article but haven't been able to make much progress:

[Improved UX with Session Sigs](https://developer.litprotocol.com/sdk/authentication/security#improved-ux-with-sessionsigs)
Could you provide guidance on how to implement session persistence or clarify how the session-related keys might help in this scenario?

Thank you in advance for your assistance!

Best regards,
Rohik

### Additional context

*No response*

**Comment by gallirohik** [comment]
Hi @a1ttech, thanks for your response, it makes sense. However, I'm noticing some unexpected behavior. If we have an active session stored in `local storage`, such as `lit-session-key` and `lit-wallet-sig`, shouldn't the user remain logged in after a page refresh?

In the [lit-pkp-auth-demo](https://github.com/LIT-Protocol/lit-pkp-auth-demo?tab=readme-ov-file) example, even after successfully logging in, refreshing the page shows the login page again, which is a bit confusing.

Could you also provide more clarity on the exact role of `lit-session-key` and `lit-wallet-sig`? Where and how should they be used to maintain the session?

Thanks again for your help!

**Comment by zach-is-my-name** [comment]
Had the same issue. Made it work using local storage for persistence. Tan
Stack query (with one of its persisters) works marvelously for handling the
dependency trio authmethod, authSig, sessionSigs - but you’re right my
expectation this would be automatically handled across refreshes had me
second guessing quite a bit until I acquiesced that it simply doesn’t
exist.  On that note v 6.9.0 introduced validateSessionSigs
https://github.com/LIT-Protocol/js-sdk/pull/642
 which helps manage expirations.

**Comment by zach-is-my-name** [comment]
How I'm managing this manually to work across refreshes: 

https://github.com/LIT-Protocol/js-sdk/pull/642#issuecomment-2414928560

**Comment by gallirohik** [comment]
@zach-is-my-name This is awesome! 😊 Thanks for sharing the PR references. really helpful!!

So, we can use [validateSessionSigs](https://v6-api-doc-lit-js-sdk.vercel.app/functions/misc_src.validateSessionSigs.html) and pass the `lit-wallet-sig` from local storage, correct?

After looking into it further, it seems that this only verifies whether the session is valid. Is there a way to use the `lit-wallet-sig` to sign a message as well?

Also, I noticed you’re storing values like `authmethod, authSig, and sessionSigs` in TanStack and that can be used for signing messages and other operations, is that right?

Thanks again for your help!

**Comment by zach-is-my-name** [comment]
> So, we can use validateSessionSigs and pass the lit-wallet-sig from local storage, correct?

You pass sessionSigs and because sessionSigs "wrap" the lit-wallet-sig (aka authsig) validateSessionSigs verifies both! 
(You'll see references to "inner" and "outer" signatures - sessionSigs is the putter, authSig (lit-wallet-sig) is the inner). 


There's also a recent related PR that formats and logs sessionSigs with this data. It should be findable with a query to PR's using "sessionSigs". 

Remember, validateSessionSigs still doesn't solve the data you mentioned getting wiped from local storage across refreshes, so the manual persistence is still necessary (for that).

**Comment by zach-is-my-name** [comment]
`Also, I noticed you’re storing values like authmethod, authSig, and sessionSigs in TanStack and that can be used for signing messages and other operations, is that right?`

Hell yeah. You need ready access to sessionSigs for _nearly everything_ including but not limited to accessing pkpWallet, feeding to executeJs for Lit Actions- so yes 🙂

**Comment by gallirohik** [comment]
Thank you, now it makes sense :) .

If I understand correctly, we essentially need  pkpPubKey (the current account’s public key) and sessionSigs (initiated after a successful login) to perform signMessage. 

So we need to persist `authMethod` & `sessionSigs` on tanstack . anyways `authSig (aka lit-wallet-sig)` is already persisted on local storage.

This approach would allow us to maintain persistent login after a page refresh without storing wallet public keys in TanStack queries.

On a page refresh:

- First, we validate if the authSig (aka lit-wallet-sig) is still valid using validateSessionSigs.
- Then, retrieve authMethod and sessionSigs from TanStack (it's a good idea to map them based on the `sig` property of `lit- wallet-sig` to avoid mismatches between authSigs and sessionSigs).
- When necessary (e.g., during signMessage or other operations), retrieve the valid PKP accounts (wallets) and use the PKP that matches the `address` property of `lit-wallet-sig`.

Please correct if my understanding / approach is wrong.

I really appreciate your time & valuable information,

Thanks

**Comment by zach-is-my-name** [comment]
> we essentially need pkpPubKey (the current account’s public key)

Yes that's the critical value to producing sessionSigs that's not being stored in local-storage, that I couldn't remember.

> So we need to persist authMethod & sessionSigs on tanstack . anyways authSig (aka lit-wallet-sig) is already persisted on local storage.

Yes, but I'll add that I'm preserving the entire chain up until and including the sessionSigs in Tanstack because:

-   authMethod is only obtained from the Lit Oauth redirect (I've set up my own Oauth, but that's another topic)
-   **_litAccount_** (which is distinct from lit-wallet-sig) has this interface export interface ```
IRelayPKP {
    /**
     * PKP token ID
     */
    tokenId: string;
    /**
     * PKP public key
     */
    publicKey: string;
    /**
     * PKP Eth address
     */
    ethAddress: string;
}
```
-  This ^ is why I store litAccount in Tanstack to have access to litAccount.publicKey
-  litAccount.publicKey is necessary for the sessionSigs generation:
     ```
   const newSessionSigs = await litNodeClient.getPkpSessionSigs({
          pkpPublicKey: litAccount.publicKey,
          authMethods: [authMethod],
          resourceAbilityRequests: [
            {
              resource: new LitPKPResource('*'),
              ability: LitAbility.PKPSigning,
            },
            {
              resource: new LitActionResource('*'),
              ability: LitAbility.LitActionExecution,
            },
            ...additionalResourceAbilityRequests
          ]
        });
        authChainLogger.info('New sessionSigs obtained');
        authChainLogger.info("4b: finish sessionSigs query")

        return newSessionSigs;
```
-  Now if I'm not mistaken, `lit-wallet-sig` is actually set in localstorage on the call to getPkpSessionSigs.  getPkpSessionSigs I believe sets that _as well as_ the `sessions-key`.  
-  sessionSigs are not stored in `localstorage` by `getPkpSessionSigs` but **I do persist them with Tanstack Query so that The user doesn't have to log in again with oauth if she/he refreshes the page.**

**Comment by gallirohik** [comment]
This makes total sense, I will implement this plan.

> Now if I'm not mistaken, lit-wallet-sig is actually set in localstorage on the call to getPkpSessionSigs. getPkpSessionSigs I believe sets that as well as the session-key.

Yes you are correct.

Thanks again for your help!
